platform :ios, '14.0'

# Standard Flutter helpers
load File.join(File.dirname(File.expand_path(__FILE__)), '..', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Helps avoid 'Module not found' issues with Swift plugins
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end