# The line below is the most important part!
target_pid = File.expand_path(File.join('..', '..', '..'), __FILE__)
load File.join(File.dirname(File.expand_path(__FILE__)), 'Generated.xcconfig')
load File.join(File.dirname(File.expand_path(__FILE__)), 'flutter_export_environment.sh') if File.exist?(File.join(File.dirname(File.expand_path(__FILE__)), 'flutter_export_environment.sh'))

# This helper is what was missing
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', '..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1] if matches
  end
  raise "FLUTTER_ROOT not found in Generated.xcconfig. Try deleting Generated.xcconfig and running flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end